import type { ResumeBundle } from "./types";

/**
 * Local mirror of core/management/commands/seed_data.py.
 * Used only if the Django API is unreachable, so the site never shows
 * empty sections during local preview or a frontend-only deploy.
 */
export const fallbackBundle: ResumeBundle = {
  stats: [
    { id: 1, label: "years building production software", value: "2+" },
    { id: 2, label: "backend performance improvement on a shipped project", value: "30%" },
    { id: 3, label: "cold outreach contacts across 6 regions", value: "100+" },
    { id: 4, label: "hours to first response from a public EU company", value: "14" },
  ],
  skills: [
    { id: 1, name: "Python", category: "languages" },
    { id: 2, name: "JavaScript (ES6+)", category: "languages" },
    { id: 3, name: "TypeScript", category: "languages" },
    { id: 4, name: "PHP", category: "languages" },
    { id: 5, name: "C++", category: "languages" },
    { id: 6, name: "HTML5", category: "languages" },
    { id: 7, name: "CSS3", category: "languages" },
    { id: 8, name: "React 19", category: "frontend" },
    { id: 9, name: "Vite", category: "frontend" },
    { id: 10, name: "Tailwind CSS", category: "frontend" },
    { id: 11, name: "TanStack Query", category: "frontend" },
    { id: 12, name: "Zustand", category: "frontend" },
    { id: 13, name: "react-hook-form", category: "frontend" },
    { id: 14, name: "Django", category: "backend" },
    { id: 15, name: "Django REST Framework", category: "backend" },
    { id: 16, name: "JWT Authentication", category: "backend" },
    { id: 17, name: "Role-Based Access Control", category: "backend" },
    { id: 18, name: "pytest", category: "backend" },
    { id: 19, name: "PostgreSQL", category: "database" },
    { id: 20, name: "MySQL", category: "database" },
    { id: 21, name: "SQLite", category: "database" },
    { id: 22, name: "Django ORM", category: "database" },
    { id: 23, name: "Git", category: "devops" },
    { id: 24, name: "GitHub", category: "devops" },
    { id: 25, name: "Vercel CI/CD", category: "devops" },
    { id: 26, name: "Agile", category: "project_mgmt" },
    { id: 27, name: "Scrum", category: "project_mgmt" },
    { id: 28, name: "Sprint Planning", category: "project_mgmt" },
    { id: 29, name: "Stakeholder Communication", category: "project_mgmt" },
  ],
  experience: [
    {
      id: 1,
      company: "SoftTechHolic",
      role: "Technical Project Coordinator & Full Stack Developer",
      location: "Rawalpindi, Pakistan (Hybrid)",
      period: "2023 — 2024",
      bullets: [
        { id: 1, text: "Led Agile sprint coordination for a 4-member cross-functional development team, managing task breakdown, milestone tracking, and on-time delivery across multiple concurrent workstreams." },
        { id: 2, text: "Translated complex business requirements into actionable technical specifications, reducing back-and-forth between stakeholders and developers by acting as the primary technical bridge." },
        { id: 3, text: "Proactively identified and resolved development blockers, maintaining sprint velocity and preventing timeline slippage across all project phases." },
        { id: 4, text: "Maintained async-first communication standards across the team, producing clear documentation, daily standups, and stakeholder status updates." },
        { id: 5, text: "Contributed full-stack development alongside coordination responsibilities, writing production-ready Python/Django backend code and JavaScript frontend components." },
      ],
    },
  ],
  education: [
    { id: 1, institution: "Virtual University of Pakistan", credential: "Bachelor of Science in Computer Science", location: "Wah Cantt, Pakistan", period: "2025 — Present", note: "Pursuing while actively working on professional projects and client outreach." },
    { id: 2, institution: "Board of Intermediate & Secondary Education", credential: "Intermediate — F.Sc Pre-Engineering", location: "Wah Cantt, Pakistan", period: "2021 — 2023", note: "" },
    { id: 3, institution: "Board of Intermediate & Secondary Education", credential: "Matriculation — Science", location: "Gujranwala Cantt, Pakistan", period: "2019 — 2021", note: "" },
  ],
  projects: [
    {
      id: 1, number: 1,
      title: "SolidPrime — Multi-Tenant B2B Operations Dashboard",
      tagline: "An operations platform that gives a B2B company one place to run customers, pipeline, projects, invoices, and tasks.",
      live_url: "https://solid-prime-b2-b-product.vercel.app",
      repo_url: "https://github.com/matifraza512-dot/SolidPrime-B2B-Product-",
      docs_url: "https://matifraza512.pythonanywhere.com/api/docs/",
      stack: "Python, Django, Django REST Framework, JWT, PostgreSQL, SQLite, pytest, React 19, TypeScript, Vite, Tailwind CSS, TanStack Query, Zustand, Vercel, PythonAnywhere, Git",
      stack_list: ["Python", "Django", "Django REST Framework", "JWT", "PostgreSQL", "SQLite", "pytest", "React 19", "TypeScript", "Vite", "Tailwind CSS", "TanStack Query", "Zustand", "Vercel", "PythonAnywhere", "Git"],
      featured: true,
      highlights: [
        { id: 1, label: "Architecture", text: "Full-stack, multi-tenant B2B operations platform built module by module — Django REST Framework backend, React 19/TypeScript/Vite frontend." },
        { id: 2, label: "Backend", text: "11 production modules with JWT authentication, role-based access control (Admin/Manager/Employee), organization-scoped querysets for tenant isolation, and an object-level permission class as a defense-in-depth backstop." },
        { id: 3, label: "Frontend", text: "TypeScript, TanStack Query for server state, Zustand for persisted auth state, react-hook-form + zod for validation, and an axios interceptor for automatic JWT refresh." },
        { id: 4, label: "Reliability engineering", text: "Root-caused a production 500 error to a missing NOT NULL constraint and fixed it with a custom UserManager and a database migration; added exception logging and a live session sync to catch a stale-permissions bug." },
        { id: 5, label: "DevOps", text: "Frontend on Vercel, backend on PythonAnywhere, zero recurring cost. GitHub as single source of truth for both repos." },
      ],
    },
    {
      id: 2, number: 2,
      title: "Personal Portfolio — Full Stack Web Application",
      tagline: "This site: a Django API behind a hand-built animated frontend, shipped with zero-downtime CI/CD.",
      live_url: "https://portfolio-6cqm.vercel.app",
      repo_url: "https://github.com/matifraza512-dot",
      docs_url: "",
      stack: "Python, Django, Django REST Framework, JWT, PostgreSQL, React 19, Vite, JavaScript (ES6+), HTML5, CSS3, Git, Vercel",
      stack_list: ["Python", "Django", "Django REST Framework", "JWT", "PostgreSQL", "React 19", "Vite", "JavaScript (ES6+)", "HTML5", "CSS3", "Git", "Vercel"],
      featured: false,
      highlights: [
        { id: 1, label: "Architecture", text: "Django REST API backend with a React 19/Vite/TypeScript frontend — full-stack ownership from database to UI." },
        { id: 2, label: "Backend", text: "5 production RESTful API endpoints (Contact, Projects, Posts, JWT Auth, Token Refresh) with JWT-based auth and a relational schema via Django ORM." },
        { id: 3, label: "Frontend", text: "Animated particle canvas, custom cursor system, scroll-reveal animations, and a mobile-first responsive layout with client-side form validation." },
        { id: 4, label: "DevOps", text: "Automated CI/CD deployment pipeline: GitHub push → Vercel build → live production, with zero-downtime deployments." },
      ],
    },
    {
      id: 3, number: 3,
      title: "Coding the Brains — Office Attendance & Workforce Management Platform",
      tagline: "A multi-tenant Django platform that replaced manual attendance sheets with role-based dashboards and face-recognition check-ins.",
      live_url: "", repo_url: "", docs_url: "",
      stack: "Python, Django, Django ORM, Face Recognition, Role-Based Access Control, Multi-Tenant Architecture",
      stack_list: ["Python", "Django", "Django ORM", "Face Recognition", "Role-Based Access Control", "Multi-Tenant Architecture"],
      featured: false,
      highlights: [
        { id: 1, label: "Platform", text: "Multi-tenant Django web application for organizational attendance tracking, with role-based dashboards for Admins, Managers, Developers, Interns, and Clients." },
        { id: 2, label: "Attendance engine", text: "Face-recognition-based attendance module alongside manual entry, enabling automated check-ins and reducing manual record-keeping." },
        { id: 3, label: "Access control", text: "Organization-scoped data access and custom permission decorators (@login_required, @role_required) enforcing role-based authorization." },
        { id: 4, label: "Sync", text: "Attendance data synchronization between HR and project-management modules, keeping status consistent across dashboards." },
      ],
    },
    {
      id: 4, number: 4,
      title: "Remote Client Outreach System",
      tagline: "A structured B2B outreach pipeline, run like a project — not a mail-merge.",
      live_url: "", repo_url: "", docs_url: "",
      stack: "Research, Segmentation, Cold Outreach, Business Development, Project Management",
      stack_list: ["Research", "Segmentation", "Cold Outreach", "Business Development", "Project Management"],
      featured: false,
      highlights: [
        { id: 1, label: "Pipeline", text: "Structured outreach pipeline targeting 100+ international e-commerce companies across 6 regions (USA, UK, Germany, France, Scotland, Washington State)." },
        { id: 2, label: "Result", text: "First response within 14 hours from AboutYou (Hamburg, DE) — a publicly traded fashion platform." },
        { id: 3, label: "Process", text: "Research, categorization, prioritization, execution, and follow-up — applied systematically to a business development goal." },
      ],
    },
  ],
};
